# =============================================================================
# Age of Mythology Retold — Game-side bridge (XS state writer + log tail)
# =============================================================================
#
# Sister to ApClient.py.  Where ApClient.py owns the AP server connection and
# the slot_data, GameClient.py owns the bridge into the running game:
#
#   1. STATE EMISSION
#      `write_aom_state(ctx)` produces `<user_folder>/trigger/aom_state.xs`,
#      a giant XS source file that archipelago.xs `#include`s.  It declares
#      generated functions like `APInitItems()`, `APInitGods()`,
#      `APApplyMinorGodSelection()`, `APInitGodPowers()`, etc.  Each call
#      regenerates the file from the latest `received_items`, so the running
#      game sees a fresh state at the next scenario load.
#
#   2. AI ECHO TAIL
#      `read_new_checks(ctx)` parses `MythRetoldAIOutputPlayer12.txt` (where
#      AoMR's aiEcho output lands) for AP-prefixed tokens:
#         AP_CHECK:<id>      — game reports a location check fired
#         AP_LOCKED:<...>    — section is locked (display warning)
#         AP_SHOP:<slot_id>  — player bought a shop slot
#         AP_TRAP_FIRED:<id> — trap acknowledged so we can advance the queue
#         AP_RAND_GP:<...>   — random god power state report
#
#   3. PERSISTENCE
#      load_/save_ pairs persist `sent_checks`, shop / trap state, and a
#      session uuid into the per-game cache directory so an interrupted
#      session restores correctly on the next launch.
#
#   4. AI XS GENERATION
#      `generate_ap_ai_xs(ctx, mods_local_dir)` — overlays per-game data into
#      ap_ai_runtime.xs and copies it into the mod's AI directory so the
#      scenario can pick it up at next load.
#
# Key file paths (relative to the player's AoMR user folder):
#   * trigger/aom_state.xs          — generated by write_aom_state
#   * trigger/archipelago.xs        — bundled, includes aom_state.xs
#   * Game/AI/ap_ai_runtime.xs      — generated by generate_ap_ai_xs
#   * MythRetoldAIOutputPlayer12.txt — AI echo log we tail
#
# Adding a new generated state field:
#   1. Add a field to AoMGameContext (this file).
#   2. Read it in ApClient.py `_on_connected` from slot_data.
#   3. Emit corresponding XS into `write_aom_state` (often as a new
#      `APInitX()` function or an extension of an existing one).
#   4. Consume the generated function in archipelago.xs via APActivateScenario
#      or APApplyItems.
#
# Adding a new AP-prefixed token:
#   1. Make archipelago.xs print the token via `aiEcho()` from a Player 12
#      AI rule.
#   2. Add a parser branch in `read_new_checks`.
#   3. Forward the parsed event to AP-side via the `client_interface`
#      callback (typically `client_interface.send_msgs(...)`).
# =============================================================================

import asyncio
import logging
import os
from dataclasses import dataclass, field
from pathlib import Path

from ..locations.Locations import aomLocationData, aomLocationType, location_id_to_name, SHOP_SLOT_ORDER
from ..items.Items import (
    aomItemData,
    AtlanteanMythUnitUnlock,
    AtlanteanUnitUnlockProgression,
    AtlanteanUnitUnlockUseful,
    MythUnitUnlockFiller,
    MythUnitUnlockProgression,
    MythUnitUnlockUseful,
    UnitUnlockProgression,
    UnitUnlockUseful,
)

logger = logging.getLogger("Client")

# -----------------------------------------------------------------------
# Item → proto unit name mapping
# Used by write_aom_state to generate APForbidItemGatedUnits().
# Only items that gate trainable units are included; resource/hero/etc.
# items have no entry here.
# -----------------------------------------------------------------------

_ITEM_TO_UNITS: dict[int, list[str]] = {}
for _item in aomItemData:
    _t = _item.type
    if isinstance(_t, (UnitUnlockProgression, UnitUnlockUseful,
                       AtlanteanUnitUnlockProgression, AtlanteanUnitUnlockUseful)):
        _ITEM_TO_UNITS[_item.id] = [_t.unit_name]
    elif isinstance(_t, (MythUnitUnlockProgression, MythUnitUnlockUseful,
                         MythUnitUnlockFiller, AtlanteanMythUnitUnlock)):
        _ITEM_TO_UNITS[_item.id] = list(_t.units)

# -----------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------

AI_OUTPUT_FILENAME = "MythRetoldAIOutputPlayer12.txt"

MOD_AI_DIR_NAME = "fott_ap_campaign"
APAI_INIT_FILENAME = "ap_ai_init.xs"
APAI_RUNTIME_FILENAME = "ap_ai_runtime.xs"

TRIGGER_FOLDER_NAME  = "trigger"
CACHE_DIR_NAME       = "ap_randomizer_cache"
AOM_STATE_FILENAME   = "aom_state.xs"

AP_CHECK_PREFIX  = "AP_CHECK:"
AP_LOCKED_PREFIX = "AP_LOCKED:"
AP_SHOP_PREFIX   = "AP_SHOP:"
AP_TRAP_PREFIX   = "AP_TRAP_FIRED:"
AP_RAND_GP_PREFIX = "AP_RAND_GP:"

GEM_ITEM_ID = 9998  # aomItemData.GEM
SHOP_SCENARIO_ID = 0  # reserved scenario ID for the shop

# Victory location IDs for scenarios 1-31 (scenario 32 is the goal, not a gem).
# campaign_val * 100 + chapter = scenario_id; victory = BASE_ID + scenario_id * 100
_BASE_ID = 0x3B0000
VICTORY_LOCATION_IDS: frozenset = frozenset(
    _BASE_ID + (campaign_val * 100 + chapter) * 100
    for campaign_val, chapters in [
        (1, range(1, 11)),  # FotT Greek 1-10
        (2, range(1, 11)),  # FotT Egyptian 11-20
        (3, range(1, 11)),  # FotT Norse 21-30
        (4, range(1, 2)),   # FotT Final 31
        (5, range(1, 13)),  # New Atlantis 501-512
        (6, range(1, 5)),   # The Golden Gift 601-604
    ]
    for chapter in chapters
)


# -----------------------------------------------------------------------
# Context
# -----------------------------------------------------------------------

@dataclass
class AoMGameContext:
    """Runtime state shared between ApClient.py and GameClient.py.

    ApClient owns the AP server connection; this struct holds the data the
    game-side bridge needs (received_items, sent_checks, slot_data echoes,
    session-replay tracking, shop & trap state).  Persisted state is cached
    under `cache_folder` keyed by `(seed, slot, world_id, session_id)` so
    replaying a generation gives a fresh start.

    Field groups:
      * Connection: user_folder, client_interface
      * Item flow:  received_items (from server), sent_checks (to server)
      * Slot data echoes: final_mode, x_scenarios_threshold,
                          random_major_gods, god_assignments,
                          minor_god_*, archaic_forbids, god_power_assignments,
                          gem_shop_enabled, relicsanity_enabled,
                          wins_to_open_shop, shop_*
      * Cache identity: ap_server / ap_seed / ap_slot / world_id / session_id
      * Trap pacing:    trap_queue, trap_ack_nonce, traps_fired_this_scenario
    """
    running: bool = True
    user_folder: str = ""
    received_items: list[int] = field(default_factory=list)
    sent_checks: set[int] = field(default_factory=set)
    client_interface: object = None
    # Slot data cached on connect for state file logic
    final_mode: int = -1           # 0=beat_x, 1=always_open, 2=atlantis_key
    x_scenarios_threshold: int = 0  # only used when final_mode == 0
    random_major_gods: bool = False
    update_buildings_for_random_god: bool = True
    god_assignments: dict = None         # scenario_id (int) → major_god int
    minor_god_assignments: dict = None   # scenario_id (int) → [tech_name, ...]
    minor_god_full: dict = None          # scenario_id (int) → {tier (int) → [chosen, rejected, is_floor]}
    archaic_forbids: dict = None         # scenario_id (int) → [unit_name, ...]
    god_power_assignments: dict = None   # scenario_id (int) → [tier1, tier2, tier3, tier4]
    # Cache identity — set on connect, used to build cache_folder path
    ap_server:   str = ""   # e.g. "archipelago.gg:38281" (informational only; not in cache key)
    ap_seed:     str = ""   # seed_name from RoomInfo
    ap_slot:     str = ""   # slot name (auth) the player connected with
    # Session UUID distinguishes replays of the same generation (same seed/slot/world_id).
    # Resolved on connect from current_session.txt under session_root, or generated fresh.
    session_id:  str = ""
    # Shop state
    wins_to_open_shop: int = 5
    world_id: int = 0
    gem_shop_enabled: bool = True
    relicsanity_enabled: bool = False
    trap_queue: list  = field(default_factory=list)   # list of trap_type ints
    trap_ack_nonce: int = 0                           # written to aom_state.xs
    traps_fired_this_scenario: int = 0                 # reset each scenario load
    purchased_slots: set  = field(default_factory=set)
    shop_obelisk_assignments: dict = field(default_factory=dict)  # obelisk_id → [loc_id,...]
    shop_item_details: dict = field(default_factory=dict)         # loc_id → {player, name, cls}
    shop_hint_config: dict  = field(default_factory=dict)         # slot_id → {type, ...}
    shop_slot_order: list   = field(default_factory=list)
    # Checks the AP server has already confirmed — used for in-memory
    # deduplication only. Never persisted to disk.
    server_known_checks: set[int] = field(default_factory=set)
    # Locked-scenario warnings already shown this connection.
    locked_warning_campaigns: set[str] = field(default_factory=set)
    # Scenario-key bundling (unlock_sets_of_scenarios option)
    unlock_sets_of_scenarios: int = 0
    scenario_to_key_id: dict = field(default_factory=dict)     # scenario_global_number → AP item id
    bundle_display_names: dict = field(default_factory=dict)   # AP item id → friendly bundle name
    starter_bundle_key_id: int | None = None
    # Reserved for compatibility with older logic. The runtime log parser now
    # scans from byte 0 on every poll after the connect-time log purge.
    log_start_offset: int = 0

    @property
    def trigger_folder(self) -> Path:
        return Path(self.user_folder) / TRIGGER_FOLDER_NAME

    @property
    def session_root(self) -> Path:
        """Folder identifying a unique multiworld generation for this slot.
        Holds current_session.txt (the active session UUID pointer) plus one
        subfolder per session UUID. Server is intentionally excluded from the
        key so a server rename / port change does not orphan progress.
        """
        def _sanitise(s: str) -> str:
            for ch in r'\/:*?"<>|':
                s = s.replace(ch, "_")
            return s.strip("._") or "_"

        seed  = _sanitise(self.ap_seed or "unknown_seed")
        slot  = _sanitise(self.ap_slot or "unknown_slot")
        world = str(self.world_id)
        return Path(self.user_folder) / CACHE_DIR_NAME / seed / slot / world

    @property
    def cache_folder(self) -> Path:
        """Per-session cache directory. Distinguishes replays of the same
        generation via session_id, so completing a game and starting fresh on
        the same seed+slot does not inherit the old game's items/checks.
        """
        sid = self.session_id or "unknown_session"
        return self.session_root / sid

    @property
    def ai_output_file(self) -> Path:
        # user_folder is e.g. C:/Users/Philip/Games/Age of Mythology Retold/76561198039446386
        # logs are at:         C:/Users/Philip/Games/Age of Mythology Retold/temp/Logs
        return Path(self.user_folder).parent / "temp" / "Logs" / AI_OUTPUT_FILENAME

    @property
    def aom_state_file(self) -> Path:
        return self.trigger_folder / AOM_STATE_FILENAME

    def ap_ai_init_file(self, mods_local_dir: Path) -> Path:
        # ap_ai_init.xs must live in the user-level Game\AI folder.
        return Path(self.user_folder) / "Game" / "AI" / APAI_INIT_FILENAME

    def ap_ai_runtime_file(self, mods_local_dir: Path) -> Path:
        # ap_ai_runtime.xs must live in the user-level Game\AI folder.
        return Path(self.user_folder) / "Game" / "AI" / APAI_RUNTIME_FILENAME


# -----------------------------------------------------------------------
# apai.xs generation
# -----------------------------------------------------------------------

def _load_ap_ai_runtime_template_text() -> str:
    r"""
    Load ap_ai_runtime.xs from the triggers folder inside the apworld zip.

    __file__ for a zip-imported module is a virtual path like:
        C:\...\aom.apworld\aom\client\GameClient.py
    That path doesn't exist on disk, so Path.read_text() fails.
    We walk up __file__'s parents to find the .apworld boundary, then
    use zipfile.ZipFile to read the template directly from the archive.
    """
    import zipfile as _zf
    try:
        # Find the .apworld file in the path hierarchy
        apworld_path = None
        for parent in [Path(__file__)] + list(Path(__file__).parents):
            if str(parent).lower().endswith(".apworld") and parent.is_file():
                apworld_path = parent
                break
        if apworld_path:
            with _zf.ZipFile(apworld_path, "r") as z:
                internal = f"aom/triggers/{APAI_RUNTIME_FILENAME}"
                if internal in z.namelist():
                    return z.read(internal).decode("utf-8")
            logger.error(f"{APAI_RUNTIME_FILENAME} not found inside {apworld_path}")
        else:
            # Not running from a zip — try plain filesystem (dev/test mode)
            template_path = Path(__file__).parent.parent / "triggers" / APAI_RUNTIME_FILENAME
            if template_path.exists():
                return template_path.read_text(encoding="utf-8")
            logger.error(f"Could not locate apworld zip and {template_path} does not exist")
    except Exception as ex:
        logger.error(f"Failed to load {APAI_RUNTIME_FILENAME} template: {ex}")
    # Minimal fallback — trap system won't work but checks still will.
    return (
        'extern int gAPCategory = -1;\n\n'
        'void main()\n'
        '{\n'
        '   gAPCategory = aiAddEchoCategory("Archipelago");\n'
        '   aiEcho("APAI startup.");\n'
        '}\n\n'
        'rule APHeartbeat\n'
        'minInterval 30\n'
        'active\n'
        '{\n'
        '   aiEcho("APAI heartbeat.");\n'
        '}\n'
    )


def _strip_generated_ap_functions(template_text: str) -> str:
    """
    Remove old generated AP bridge functions so the template can safely be
    regenerated without duplicate symbol definitions.
    """
    stripped_lines: list[str] = []
    for line in template_text.splitlines():
        s = line.strip()
        if s.startswith("void APCheck_"):
            continue
        if s.startswith("void APLocked_"):
            continue
        if s.startswith("void APShop_"):
            continue
        if s.startswith("void APShopSignal("):
            continue
        if s.startswith("void APTrapFiredSignal("):
            continue
        stripped_lines.append(line.rstrip())
    return "\n".join(stripped_lines).rstrip() + "\n"


def generate_ap_ai_xs(ctx: AoMGameContext, mods_local_dir: Path) -> None:
    r"""
    Generate Game\AI\ap_ai_runtime.xs from the packaged triggers/ap_ai_runtime.xs
    template, then append generated AP bridge functions for Player 12.
    Called on every client connect so the live runtime AI file is always current.
    """
    # mods_local_dir kept for call-site compatibility.
    _ = mods_local_dir

    template_text = _strip_generated_ap_functions(_load_ap_ai_runtime_template_text())

    lines = [
        template_text.rstrip(),
        "",
        "// -----------------------------------------------------------------------",
        "// AUTO-GENERATED AP BRIDGE FUNCTIONS",
        "// -----------------------------------------------------------------------",
        "",
    ]

    generated_count = 0

    for location in aomLocationData:
        if location.type == aomLocationType.COMPLETION:
            continue
        loc_id = location.id
        lines.append(f'void APCheck_{loc_id}() {{ aiEcho("{AP_CHECK_PREFIX}{loc_id}"); }}')
        generated_count += 1

    lines.append("")

    for campaign in ["Greek", "Egyptian", "Norse", "Final", "NewAtlantis", "GoldenGift"]:
        lines.append(f'void APLocked_{campaign}() {{ aiEcho("{AP_LOCKED_PREFIX}{campaign}"); }}')
        generated_count += 1

    lines.append("")

    for slot_index in range(1, len(SHOP_SLOT_ORDER) + 1):
        lines.append(f'void APShop_{slot_index}() {{ aiEcho("{AP_SHOP_PREFIX}IDX:{slot_index}"); }}')
        generated_count += 1

    lines.append("")
    lines.append(f'void APTrapFiredSignal() {{ aiEcho("AP_TRAP_FIRED:"); }}')

    lines.append("")
    content = "\n".join(lines)

    runtime_path = ctx.ap_ai_runtime_file(mods_local_dir)
    runtime_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        runtime_path.write_text(content, encoding="utf-8")
        logger.info(f"Generated {runtime_path} with {generated_count} AP bridge functions.")
    except Exception as ex:
        logger.error(f"Failed to write {APAI_RUNTIME_FILENAME}: {ex}")

# -----------------------------------------------------------------------
# aom_state.xs writing
# -----------------------------------------------------------------------

def _get_has_atlantis(ctx: AoMGameContext, received_set: set) -> int:
    """
    Returns 9004 if the player should have Atlantis access, 9000 otherwise.
    In beat_x_scenarios mode, derives access from the local sent_checks count
    so the game state matches the UI without relying on AP event locations.
    In atlantis_key mode, requires the actual item to be received.
    In always_open mode, always returns 9004.
    """
    ATLANTIS_KEY = 3510
    if ATLANTIS_KEY in received_set:
        return 9004
    if ctx.final_mode == 1:  # always_open
        return 9004
    if ctx.final_mode == 0 and ctx.x_scenarios_threshold > 0:  # beat_x_scenarios
        from ..locations.Locations import aomLocationData, aomLocationType
        # Count victories across all activated campaigns (FotT 1-30, NA 501-512,
        # GG 601-604). Filtering by global_number <= 30 used to silently exclude
        # NA and GG victories, leaving the in-game state at 9000 even when the
        # AP UI showed the Atlantis Key as obtained.
        beaten = sum(
            1 for loc in aomLocationData
            if loc.type == aomLocationType.VICTORY
            and (loc.scenario.global_number <= 30
                 or 501 <= loc.scenario.global_number <= 512
                 or 601 <= loc.scenario.global_number <= 604)
            and loc.id in ctx.sent_checks
        )
        if beaten >= ctx.x_scenarios_threshold:
            return 9004
    return 9000


# -----------------------------------------------------------------------
# Building transformation data for UpdateBuildingsForRandomGod
# -----------------------------------------------------------------------
_GOD_TO_CIV = {
    1: "Greek", 2: "Greek", 3: "Greek",        # Zeus, Poseidon, Hades
    4: "Egyptian", 5: "Egyptian", 6: "Egyptian", # Ra, Isis, Set
    7: "Norse", 8: "Norse", 9: "Norse",          # Thor, Odin, Loki
    10: "Atlantean", 11: "Atlantean", 12: "Atlantean",  # Kronos, Oranos, Gaia
}
_CLASSICAL_BLDGS = {
    "Greek":     ["MilitaryAcademy", "ArcheryRange", "Stable"],
    "Egyptian":  ["Barracks"],
    "Norse":     ["Longhouse", "GreatHall"],
    "Atlantean": ["MilitaryBarracks", "CounterBarracks"],
}
_HEROIC_BLDGS = {
    "Greek":     ["Fortress"],
    "Egyptian":  ["MigdolStronghold", "SiegeWorks"],
    "Norse":     ["HillFort"],
    "Atlantean": ["Palace"],
}
# Scenarios where ally players also need building transforms to match P1's random god.
# Key = scenario global_number, value = player IDs to transform.
# Default (not listed) = [1] (player 1 only).
# Scenario 7:  player 1 is absent; player 3 is the allied human player.
# Scenario 16: player 4 mirrors player 1's god (fott 16b).
# Scenario 26: players 3-5 are allied and share player 1's god.
# Scenario 511 (NA 11): players 2-5 are allied and share player 1's god.
_BLDG_PLAYER_OVERRIDE = {7: [3], 16: [4], 26: [3, 4, 5], 511: [2, 3, 4, 5]}

def write_aom_state(ctx: AoMGameContext) -> None:
    """Generate `<trigger_folder>/aom_state.xs` from the current game context.

    This is THE bridge between the AP server (Python) and the running game
    (XS).  archipelago.xs `#include`s the file and reads its globals on every
    scenario activation:

      * gAPItems[]                — flag bytes + received item ids
      * APInitGods()              — emits per-scenario god QV assignments
      * APInitStartingAgeTechs    — (removed; see git history; was a dup
                                    of APApplyMinorGodSelection floor)
      * APApplyMinorGodSelection  — chosen/rejected minor god per tier
      * APInitGodPowers()         — random god power per tier per scenario
      * APForbidItemGatedUnits    — list of units to forbid until items arrive
      * APInitArchaicForbids      — units to forbid based on civ swap
      * APInitShopState           — gem shop assignments and per-slot details

    Called from the game loop (`game_loop`) on a heartbeat AND on every
    `on_items_received`.  Idempotent — overwrites the file in full.

    The file is a giant XS source with hand-formatted indentation; do not
    reorder branches without checking archipelago.xs's expectations
    (notably the gAPItems[] index conventions for the leading flags).
    """

    """
    Write aom_state.xs to the trigger folder.
    Contains received item IDs, campaign ID, and civ override.
    XS reads this at scenario load time via include.
    """
    count = len(ctx.received_items)
    # XS arrays require size >= 1
    array_size = max(count, 1)

    # Derive campaign_id from the most recently received check location ID
    # location_id = BASE_ID + scenario_id * 100 + local_id
    # campaign_id = (location_id - BASE_ID) // 10000
    BASE_ID = 0x3B0000
    campaign_id = 0
    for loc_id in ctx.sent_checks:
        derived = (loc_id - BASE_ID) // 10000
        if 1 <= derived <= 4:
            campaign_id = derived
            break

    # Prepend flags at indices 0-5:
    #   [0] = 9001 if Greek Scenarios in items,    else 9000
    #   [1] = 9002 if Egyptian Scenarios in items, else 9000
    #   [2] = 9003 if Norse Scenarios in items,    else 9000
    #   [3] = 9004 if Atlantis Key in items,       else 9000
    #   [4] = 9100 + campaign_id
    #   [5] = 9010 if random_major_gods is on,             else 9000
    #   [6] = 9010 if gem_shop is enabled,          else 9000
    #   [7] = 9005 if Unlock New Atlantis in items,         else 9000
    #   [8] = 9006 if Unlock The Golden Gift in items,      else 9000
    # Real items start at index 9.
    GREEK_SCENARIOS      = 3500
    EGYPTIAN_SCENARIOS   = 3501
    NORSE_SCENARIOS      = 3502
    UNLOCK_NEW_ATLANTIS  = 3503
    UNLOCK_GOLDEN_GIFT   = 3504
    ATLANTIS_KEY         = 3510
    received_set = set(ctx.received_items)
    flags = [
        9001 if GREEK_SCENARIOS    in received_set else 9000,
        9002 if EGYPTIAN_SCENARIOS in received_set else 9000,
        9003 if NORSE_SCENARIOS    in received_set else 9000,
        _get_has_atlantis(ctx, received_set),
        9100 + campaign_id,                      # index 4: campaign ID
        9010 if ctx.random_major_gods else 9000,         # index 5: random_major_gods flag
        9010 if ctx.gem_shop_enabled else 9000,  # index 6: gem_shop flag
        9005 if UNLOCK_NEW_ATLANTIS in received_set else 9000,  # index 7
        9006 if UNLOCK_GOLDEN_GIFT  in received_set else 9000,  # index 8
    ]
    items_with_flags = flags + list(ctx.received_items)
    total = len(items_with_flags)

    lines = []
    lines.append("void APInitItems()")
    lines.append("{")
    lines.append(f"    gAPItemCount = {total};")
    lines.append(f"    gAPItems = new int({total}, 0);")
    for i, item_id in enumerate(items_with_flags):
        lines.append(f"    gAPItems[{i}] = {item_id};")
    lines.append("}")

    # Random_Major_Gods — APInitGods() sets quest vars for /gods command
    lines.append("")
    lines.append("void APInitGods()")
    lines.append("{")
    # Iterate all scenario IDs that have vanilla god assignments (FotT + NA + GG)
    all_scenario_ids = sorted(ctx.god_assignments.keys()) if (ctx.random_major_gods and ctx.god_assignments) else list(range(1, 33))
    for scenario_id in all_scenario_ids:
        if ctx.random_major_gods and ctx.god_assignments and scenario_id in ctx.god_assignments:
            god_val = ctx.god_assignments[scenario_id]
        else:
            god_val = 0
        lines.append(f"    trQuestVarSet(\"APGod{scenario_id}\", {god_val});")
    lines.append("}")

    # APApplyMinorGodSelection — called from APApplyAgeUnlocks() every time items
    # are processed. For floor tiers (tier <= starting age) the seeded "chosen"
    # minor god is researched (status 2) and the other forced to 0. For above-
    # floor tiers, both options are made researchable (status 1) once ageCount
    # >= tier so the player picks freely; otherwise both are 0.
    lines.append("")
    lines.append("void APApplyMinorGodSelection(int ageCount = 0)")
    lines.append("{")
    if ctx.minor_god_full:
        for scenario_id in sorted(ctx.minor_god_full.keys()):
            tier_data = ctx.minor_god_full.get(scenario_id) or {}
            if not tier_data:
                continue
            lines.append(f"    if (gAPScenarioId == {scenario_id})")
            lines.append("    {")
            for tier in sorted(tier_data.keys()):
                entry   = tier_data[tier]
                chosen   = entry[0]
                rejected = entry[1]
                is_floor = entry[2]
                if is_floor:
                    lines.append(f"        trTechSetStatus(1, {chosen}, 2);")
                    lines.append(f"        trTechSetStatus(1, {rejected}, 0);")
                else:
                    # Above-floor tier: both options researchable once the player
                    # has enough age unlocks. Don't force one — let the player
                    # pick freely between the two minor gods at age-up.
                    lines.append(f"        if (ageCount >= {tier})")
                    lines.append(f"        {{")
                    lines.append(f"            trTechSetStatus(1, {chosen}, 1);")
                    lines.append(f"            trTechSetStatus(1, {rejected}, 1);")
                    lines.append(f"        }}")
                    lines.append(f"        else")
                    lines.append(f"        {{")
                    lines.append(f"            trTechSetStatus(1, {chosen}, 0);")
                    lines.append(f"            trTechSetStatus(1, {rejected}, 0);")
                    lines.append(f"        }}")
            lines.append("    }")
    lines.append("}")

    # APInitGodPowers — assigns the random god power for each scenario
    # to the four global string vars gAPRandGP1..4 based on the current
    # APScenarioID. Called from APActivateScenario.
    lines.append("")
    lines.append("void APInitGodPowers()")
    lines.append("{")
    lines.append("    int scenId = trQuestVarGet(\"APScenarioID\");")
    lines.append("    gAPRandGP1 = \"\";")
    lines.append("    gAPRandGP2 = \"\";")
    lines.append("    gAPRandGP3 = \"\";")
    lines.append("    gAPRandGP4 = \"\";")
    if ctx.god_power_assignments:
        for scenario_id in sorted(ctx.god_power_assignments.keys()):
            powers = ctx.god_power_assignments.get(scenario_id) or []
            if not powers or len(powers) < 4:
                continue
            lines.append(f"    if (scenId == {scenario_id})")
            lines.append("    {")
            lines.append(f'        gAPRandGP1 = "{powers[0]}";')
            lines.append(f'        gAPRandGP2 = "{powers[1]}";')
            lines.append(f'        gAPRandGP3 = "{powers[2]}";')
            lines.append(f'        gAPRandGP4 = "{powers[3]}";')
            lines.append("    }")
    lines.append("}")

    # APForbidVanillaArchaicUnits — forbids units from vanilla god/civ
    # that should not be available when the assigned god differs.
    lines.append("")
    lines.append("void APForbidVanillaArchaicUnits()")
    lines.append("{")
    lines.append("    int scenId = trQuestVarGet(\"APScenarioID\");")
    if ctx.archaic_forbids:
        for scenario_id, units in ctx.archaic_forbids.items():
            lines.append(f"    if (scenId == {scenario_id})")
            lines.append("    {")
            for unit in units:
                lines.append(f"        trForbidProtounit(1, \"{unit}\");")
            lines.append("    }")
    lines.append("}")

    # APForbidItemGatedUnits — forbids every unit whose unlock item has not yet
    # been received.  Units whose items HAVE been received are not touched at
    # all, so the game's natural civ / age / minor-god prerequisites still apply.
    lines.append("")
    lines.append("void APForbidItemGatedUnits()")
    lines.append("{")
    for item_id, units in _ITEM_TO_UNITS.items():
        if item_id not in received_set:
            for unit in units:
                lines.append(f"    trForbidProtounit(1, \"{unit}\");")
    # NA 7 (507) requires Rocs to complete — always unforbid them regardless of items.
    lines.append("    if (gAPScenarioId == 507) { trUnforbidProtounit(1, \"Roc\"); }")
    lines.append("}")

    # APInitScenarioKeys — sets quest vars APHasKey<scenarioId> = 1 if the
    # player holds the Scenario Key for that scenario.  When the
    # unlock_sets_of_scenarios option is 0 this emits a sentinel
    # APScenarioKeysActive=0 so XS can short-circuit.
    lines.append("")
    lines.append("void APInitScenarioKeys()")
    lines.append("{")
    usos = int(getattr(ctx, "unlock_sets_of_scenarios", 0))
    lines.append(f'    trQuestVarSet("APScenarioKeysActive", {1 if usos > 0 else 0});')
    if usos > 0 and ctx.scenario_to_key_id:
        for sid, kid in sorted(ctx.scenario_to_key_id.items()):
            held = 1 if kid in received_set else 0
            lines.append(f'    trQuestVarSet("APHasKey{sid}", {held});')
    lines.append("}")

    # NOTE: Previously emitted APUnforbidUnlockedUnits() here, which called
    # trUnforbidProtounit for every unit whose item HAD been received. That
    # bypassed the game's natural civ / age / minor-god prerequisites — e.g.
    # Thor with the "Greek Heroic Myth Units" item could train Nemean Lions
    # without Aphrodite, and "Norse Mythic Myth Units" let any Norse god
    # train Fire Giants without Hel. APReapplyUnitUnlocks now calls
    # APForbidItemGatedUnits instead, which forbids only un-received units
    # and leaves received-item units to the engine's natural gating.

    # ----------------------------------------------------------------
    # APShopStateInit — sets shop globals and per-obelisk labels.
    # ----------------------------------------------------------------

    PROG_INFO_ID   = 9997
    info_level     = sum(1 for i in ctx.received_items if i == PROG_INFO_ID)
    gems_earned    = sum(1 for i in ctx.received_items if i == GEM_ITEM_ID)
    available_gems = max(0, gems_earned - len(ctx.purchased_slots))
    update_bldgs_on = ctx.update_buildings_for_random_god

    def _xs(s): lines.append(s)
    def _cls_rank(c): return {"trap":-1,"filler":0,"useful":1,"progression":2}.get(c,-1)
    def _cls_disp(c): return {"trap":"Trap","filler":"Filler","useful":"Useful","progression":"Advancement"}.get(c,"?")
    def _sanitize_xs_str(s):
        """Transliterate non-ASCII characters to their closest ASCII equivalent.
        XS string literals only support ASCII; accented/special chars cause token errors."""
        import unicodedata
        return unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")

    _xs("")
    _xs("void APShopStateInit()")
    _xs("{")
    _xs(f"    gAPShopAvailableGems = {available_gems};")
    _xs(f"    gAPShopTierThreshold = {ctx.wins_to_open_shop};")
    _beaten = len(ctx.sent_checks & VICTORY_LOCATION_IDS)
    _xs('    trQuestVarSet("APBeatenScenarios", ' + str(_beaten) + ");")
    _xs('    trQuestVarSet("APRandom_Major_Gods", ' + ('1' if ctx.random_major_gods else '0') + ");")

    for _sid in ctx.shop_slot_order:
        _pv = "true" if _sid in ctx.purchased_slots else "false"
        _xs(f"    gAPShopPurchased_{_sid} = {_pv};")
        _xs('    trQuestVarSet("APPurchased_' + _sid + '", ' + ('1' if _sid in ctx.purchased_slots else '0') + ");")

    for _oid, _lids in ctx.shop_obelisk_assignments.items():
        _det = [ctx.shop_item_details.get(_l) for _l in _lids if ctx.shop_item_details.get(_l)]
        _n   = len(_det)

        # Main recipient = player with most items in this obelisk
        def _main_recipient(det):
            from collections import Counter
            if not det: return "?"
            counts = Counter(d.get("player_name","?") for d in det)
            return counts.most_common(1)[0][0]

        if not _det or info_level == 0:
            _lbl = "? items\\n? is rarest\\n?: main recipient"
        elif info_level == 1:
            _lbl = str(_n) + " items\\n? is rarest\\n?: main recipient"
        elif info_level == 2:
            _top = _cls_disp(max((_d.get("classification","filler") for _d in _det), key=_cls_rank))
            _lbl = str(_n) + " items\\n" + _top + " is rarest\\n?: main recipient"
        elif info_level == 3:
            _top = _cls_disp(max((_d.get("classification","filler") for _d in _det), key=_cls_rank))
            _pl  = _sanitize_xs_str(_main_recipient(_det))
            _lbl = str(_n) + " items\\n" + _top + " is rarest\\n" + _pl + ": main recipient"
        else:
            # Level 4: show count of rarest item type
            _top     = max((_d.get("classification","filler") for _d in _det), key=_cls_rank)
            _top_disp = _cls_disp(_top)
            _top_cnt = sum(1 for _d in _det if _d.get("classification","filler") == _top)
            _pl      = _sanitize_xs_str(_main_recipient(_det))
            _lbl = (str(_n) + " items\\n" + _top_disp + " is rarest\\n\\n"
                    + str(_top_cnt) + " " + _top_disp + " items\\n" + _pl + ": main recipient")
        _lbl = _lbl.replace('"', '\\\\"'  )
        _xs('    gAPShopLabel_' + _oid + ' = "' + _lbl + '";')

    for _sid, _hcfg in ctx.shop_hint_config.items():
        if _hcfg.get("type") == "progressive_info":
            _lbl = "Better Shop Information"
        else:
            _rng = _hcfg.get("missions_range", (1,2))
            _lbl = "Hints for " + str(_rng[0]) + "-" + str(_rng[1]) + " missions"
        _xs('    gAPShopLabel_' + _sid + ' = "' + _lbl + '";')

    _xs("}")

    # Generate APTrapQueueInit — called from APActivateScenario
    _xs("")
    _xs("void APTrapQueueInit()")
    _xs("{")
    _xs(f"    gAPTrapQueueSize = {len(ctx.trap_queue)};")
    if ctx.trap_queue:
        _xs(f"    gAPTrapQueue = new int({len(ctx.trap_queue)}, 0);")
        for _ti, _tt in enumerate(ctx.trap_queue):
            _xs(f"    gAPTrapQueue[{_ti}] = {_tt};")
    _xs('    trQuestVarSet("APTrapAckNonce", ' + str(ctx.trap_ack_nonce) + ");")
    _xs('    trQuestVarSet("APTrapsFiredThisScenario", 0);')
    _xs("}")

    # Generate APTransformBuildings() — data-only, no tr* calls.
    # Writes scenario→building transform pairs as XS int/string arrays.
    # Execution (tr* calls) lives in archipelago.xs APTransformBuildings().
    update_bldgs_on2 = ctx.update_buildings_for_random_god
    _xs("")
    _xs("extern int      gAPBldgTransformCount = 0;")
    _xs("extern int[]    gAPBldgScen           = default;")
    _xs("extern int[]    gAPBldgPlayer         = default;")
    _xs("extern string[] gAPBldgFrom           = default;")
    _xs("extern string[] gAPBldgTo1            = default;")
    _xs("extern string[] gAPBldgTo2            = default;")
    _xs("")
    _xs("void APLoadBuildingTransforms()")
    _xs("{")
    _xs("    gAPBldgTransformCount = 0;")
    if update_bldgs_on2 and ctx.god_assignments:
        _vanilla_gods2 = {
            1: 2, 2: 2, 3: 2, 4: 2,
            5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1,
            11: 4, 12: 5, 13: 6, 14: 4, 15: 4,
            16: 3,
            17: 5, 18: 5, 19: 4, 20: 4,
            21: 1,
            22: 8, 23: 8,
            24: 9, 25: 9,
            26: 7, 27: 7, 28: 7,
            29: 8, 30: 8,
            31: 1, 32: 1,
            # New Atlantis (APScenarioIDs 501-512)
            501: 11, 502: 10, 503: 10, 504: 10, 505: 10, 506: 10,
            507:  5, 508:  6, 509:  8, 510: 12, 511: 11, 512: 12,
            # The Golden Gift (APScenarioIDs 601-604)
            601: 8, 602: 9, 603: 9, 604: 8,
        }
        _pairs = []  # list of (scenId, targetPlayer, fromProto, toProto1, toProto2)
        for _sid, _vgod in sorted(_vanilla_gods2.items()):
            _rgod = ctx.god_assignments.get(_sid, _vgod)
            _vc   = _GOD_TO_CIV.get(_vgod, "Greek")
            _rc   = _GOD_TO_CIV.get(_rgod, "Greek")
            if _vc == _rc:
                continue
            _players = _BLDG_PLAYER_OVERRIDE.get(_sid, [1])
            for _tp in _players:
                for _from in _CLASSICAL_BLDGS[_vc]:
                    _to = _CLASSICAL_BLDGS[_rc]
                    _pairs.append((_sid, _tp, _from, _to[0], _to[1] if len(_to)>1 else ""))
                for _from in _HEROIC_BLDGS[_vc]:
                    _to = _HEROIC_BLDGS[_rc]
                    _pairs.append((_sid, _tp, _from, _to[0], _to[1] if len(_to)>1 else ""))
        # Size all arrays before assigning by index (XS requires this)
        _xs(f"    gAPBldgScen   = new int({len(_pairs)}, 0);")
        _xs(f"    gAPBldgPlayer = new int({len(_pairs)}, 1);")
        _xs(f'    gAPBldgFrom   = new string({len(_pairs)}, "");')
        _xs(f'    gAPBldgTo1    = new string({len(_pairs)}, "");')
        _xs(f'    gAPBldgTo2    = new string({len(_pairs)}, "");')
        for _i, (_sid, _tp, _fr, _t1, _t2) in enumerate(_pairs):
            _xs(f'    gAPBldgScen[{_i}]    = {_sid};')
            _xs(f'    gAPBldgPlayer[{_i}]  = {_tp};')
            _xs(f'    gAPBldgFrom[{_i}]    = "{_fr}";')
            _xs(f'    gAPBldgTo1[{_i}]     = "{_t1}";')
            _xs(f'    gAPBldgTo2[{_i}]     = "{_t2}";')
        _xs(f"    gAPBldgTransformCount = {len(_pairs)};")
    _xs("}")

    # Set APUpdateBldgs quest var in APShopStateInit so archipelago.xs knows option state
    # Patch it into the existing APShopStateInit by inserting before closing brace
    # We do this by re-finding and replacing the end of APShopStateInit generation

    # ----------------------------------------------------------------
    # APRelicCounterInit / APCountRelicCheck
    # Generates the relic counter setup and increment functions.
    # APRelicCounterInit() is called from APActivateScenario in archipelago.xs.
    # APCountRelicCheck(id) is called from APProcessQueuedCheck in archipelago.xs.
    # ----------------------------------------------------------------
    from ..locations.Locations import aomLocationData as _all_locs, aomLocationType as _locType
    from ..items.Items import BASE_ID as _RELIC_BASE_ID

    # Build: APScenarioID (global_number) → (internal scenario.id, relic count)
    _relic_scenario_map: dict = {}
    for _rloc in _all_locs:
        if _rloc.type == _locType.RELIC:
            _gn  = _rloc.scenario.global_number
            _sid = _rloc.scenario.id
            if _gn not in _relic_scenario_map:
                _relic_scenario_map[_gn] = (_sid, 0)
            _relic_scenario_map[_gn] = (_relic_scenario_map[_gn][0], _relic_scenario_map[_gn][1] + 1)

    _relicsanity = ctx.relicsanity_enabled

    _xs("")
    _xs("extern int gAPHasRelicCounter = 0;")
    _xs("")
    _xs("void APRelicCounterInit()")
    _xs("{")
    _xs("    gAPHasRelicCounter = 0;")
    if _relicsanity and _relic_scenario_map:
        _xs("    int _scenId = trQuestVarGet(\"APScenarioID\");")
        _first = True
        for _gn in sorted(_relic_scenario_map.keys()):
            _sid, _cnt = _relic_scenario_map[_gn]
            _kw = "if" if _first else "else if"
            _first = False
            _xs(f"    {_kw} (_scenId == {_gn})")
            _xs( "    {")
            _xs(f'        trCounterAddGenericXS("Archipelago Relics Checked", "Archipelago Relics Checked", "", "", -1, 0, {_cnt}, false, true);')
            _xs( '        trCounterPersistent("Archipelago Relics Checked", true);')
            _xs( "        gAPHasRelicCounter = 1;")
            _xs( "    }")
    _xs("    if (gAPHasRelicCounter == 0) { trSetCounterDisplay(\"No Archipelago Relics\"); }")
    _xs("}")
    _xs("")
    _xs("void APCountRelicCheck(int id = 0)")
    _xs("{")
    _xs("    if (gAPHasRelicCounter == 0) { return; }")
    if _relicsanity and _relic_scenario_map:
        _xs("    int _scenId2 = trQuestVarGet(\"APScenarioID\");")
        _first = True
        for _gn in sorted(_relic_scenario_map.keys()):
            _sid, _cnt = _relic_scenario_map[_gn]
            _base_rid  = _RELIC_BASE_ID + _sid * 100 + 10
            _max_rid   = _base_rid + _cnt - 1
            _kw = "if" if _first else "else if"
            _first = False
            _xs(f"    {_kw} (_scenId2 == {_gn} && id >= {_base_rid} && id <= {_max_rid})")
            _xs( "    {")
            _xs( "        trCounterIncrementManual(\"Archipelago Relics Checked\", 1);")
            _xs( "    }")
    _xs("}")

    # ----------------------------------------------------------------
    # APInitSentChecks / APIsAlreadyChecked
    # Writes the union of sent_checks | server_known_checks into XS so
    # APShowQueuedCheckMessage can suppress messages for already-checked
    # locations (e.g. replaying a mission, or force-released checks).
    # ----------------------------------------------------------------
    _already_checked = sorted(ctx.sent_checks | ctx.server_known_checks)
    _ac_count = len(_already_checked)
    _ac_size  = max(_ac_count, 1)
    _xs("")
    _xs(f"extern int   gAPSentCheckCount = 0;")
    _xs(f"extern int[] gAPSentChecks     = default;")
    _xs("")
    _xs("void APInitSentChecks()")
    _xs("{")
    _xs(f"    gAPSentCheckCount = {_ac_count};")
    _xs(f"    gAPSentChecks = new int({_ac_size}, 0);")
    for _aci, _acid in enumerate(_already_checked):
        _xs(f"    gAPSentChecks[{_aci}] = {_acid};")
    _xs("}")
    _xs("")
    _xs("bool APIsAlreadyChecked(int id = 0)")
    _xs("{")
    _xs("    int _i = 0;")
    _xs("    while (_i < gAPSentCheckCount)")
    _xs("    {")
    _xs("        if (gAPSentChecks[_i] == id) { return (true); }")
    _xs("        _i++;")
    _xs("    }")
    _xs("    return (false);")
    _xs("}")

    content = "\n".join(lines) + "\n"

    try:
        ctx.trigger_folder.mkdir(parents=True, exist_ok=True)
        ctx.aom_state_file.write_text(content, encoding="utf-8")
        logger.debug(f"Wrote aom_state.xs with {len(ctx.received_items)} items.")
    except Exception as ex:
        logger.error(f"Failed to write aom_state.xs: {ex}")


# -----------------------------------------------------------------------
# AI output file reading
# -----------------------------------------------------------------------

SESSION_POINTER_FILENAME = "current_session.txt"


def _new_session_uuid() -> str:
    """Generate a fresh session uuid.  A 'session' is one playthrough of a
    given (seed, slot, world_id) triple — repeatedly playing the same gen
    creates new sessions to avoid persistent-state contamination."""
    import uuid
    return uuid.uuid4().hex


def load_or_create_session_id(ctx: AoMGameContext) -> str:
    """Resolve the active session UUID for the current (seed, slot, world_id).
    Reads session_root/current_session.txt if present; otherwise generates a
    new UUID and writes the pointer. Sets ctx.session_id and returns it.
    """
    root = ctx.session_root
    pointer = root / SESSION_POINTER_FILENAME
    sid = ""
    try:
        if pointer.exists():
            sid = pointer.read_text(encoding="utf-8").strip()
    except Exception as ex:
        logger.warning(f"Failed to read session pointer {pointer}: {ex}")
    if not sid:
        sid = _new_session_uuid()
        try:
            root.mkdir(parents=True, exist_ok=True)
            pointer.write_text(sid, encoding="utf-8")
            logger.info(f"Started new session {sid} at {root}")
        except Exception as ex:
            logger.warning(f"Failed to write session pointer {pointer}: {ex}")
    else:
        logger.info(f"Resumed session {sid} at {root}")
    ctx.session_id = sid
    return sid


def start_new_session(ctx: AoMGameContext) -> str:
    """Generate a fresh session UUID for the current (seed, slot, world_id),
    overwrite the pointer, and clear in-memory game state so nothing from the
    previous session bleeds into the new one. Old session folders are left on
    disk; /purge_aom_cache removes them. Returns the new UUID.
    """
    sid = _new_session_uuid()
    root = ctx.session_root
    try:
        root.mkdir(parents=True, exist_ok=True)
        (root / SESSION_POINTER_FILENAME).write_text(sid, encoding="utf-8")
    except Exception as ex:
        logger.error(f"Failed to write new session pointer: {ex}")
    ctx.session_id = sid

    ctx.received_items     = []
    ctx.sent_checks        = set()
    ctx.server_known_checks = set()
    ctx.locked_warning_campaigns = set()
    ctx.trap_queue         = []
    ctx.trap_ack_nonce     = 0
    ctx.traps_fired_this_scenario = 0
    ctx.purchased_slots    = set()
    logger.info(f"New session started: {sid}")
    return sid


def save_trap_state(ctx: AoMGameContext) -> None:
    """Persist trap_queue to the session cache directory."""
    import json
    try:
        ctx.cache_folder.mkdir(parents=True, exist_ok=True)
        path = ctx.cache_folder / "ap_trap_state.json"
        path.write_text(json.dumps({"trap_queue": ctx.trap_queue}), encoding="utf-8")
    except Exception as ex:
        logger.warning(f"Failed to save trap state: {ex}")


def load_trap_state(ctx: AoMGameContext) -> None:
    """Load persisted trap_queue for the current session."""
    import json
    try:
        path = ctx.cache_folder / "ap_trap_state.json"
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            ctx.trap_queue = data.get("trap_queue", [])
            logger.info(f"Loaded trap state: {len(ctx.trap_queue)} trap(s) queued.")
        else:
            ctx.trap_queue = []
    except Exception as ex:
        logger.warning(f"Failed to load trap state: {ex}")
        ctx.trap_queue = []


def save_shop_state(ctx: AoMGameContext) -> None:
    """Persist purchased_slots to the session cache directory."""
    import json
    try:
        ctx.cache_folder.mkdir(parents=True, exist_ok=True)
        path = ctx.cache_folder / "ap_shop_state.json"
        path.write_text(json.dumps({"purchased_slots": list(ctx.purchased_slots)}), encoding="utf-8")
    except Exception as ex:
        logger.warning(f"Failed to save shop state: {ex}")


def load_shop_state(ctx: AoMGameContext) -> None:
    """Load persisted purchased_slots for the current session."""
    import json
    try:
        path = ctx.cache_folder / "ap_shop_state.json"
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            ctx.purchased_slots = set(data.get("purchased_slots", []))
            logger.info(f"Loaded shop state: {len(ctx.purchased_slots)} purchased slot(s).")
        else:
            ctx.purchased_slots = set()
            logger.info("No shop state found for this session — starting fresh.")
    except Exception as ex:
        logger.warning(f"Failed to load shop state: {ex}")
        ctx.purchased_slots = set()


def save_sent_checks(ctx: AoMGameContext) -> None:
    """Persist sent_checks to the session cache directory so dropped checks survive restarts."""
    import json
    try:
        ctx.cache_folder.mkdir(parents=True, exist_ok=True)
        path = ctx.cache_folder / "ap_sent_checks.json"
        path.write_text(json.dumps({"sent_checks": list(ctx.sent_checks)}), encoding="utf-8")
    except Exception as ex:
        logger.warning(f"Failed to save sent checks: {ex}")


def load_sent_checks(ctx: AoMGameContext) -> None:
    """Load persisted sent_checks for the current session."""
    import json
    try:
        path = ctx.cache_folder / "ap_sent_checks.json"
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            ctx.sent_checks = set(data.get("sent_checks", []))
            logger.info(f"Loaded sent checks: {len(ctx.sent_checks)} check(s).")
        else:
            ctx.sent_checks = set()
    except Exception as ex:
        logger.warning(f"Failed to load sent checks: {ex}")
        ctx.sent_checks = set()


def _resolve_shop_signal(ctx: AoMGameContext, slot_id: str) -> list[int]:
    """
    Process a shop purchase signal for the given slot_id.
    For item slots: returns AP location IDs to check.
    For hint slots: fires hint requests and returns empty list.
    Marks the slot as purchased and rewrites aom_state.xs either way.
    """
    if not slot_id:
        logger.warning("Empty shop signal slot_id.")
        return []

    if slot_id in ctx.purchased_slots:
        logger.debug(f"Shop slot {slot_id} already purchased, ignoring duplicate signal.")
        return []

    ctx.purchased_slots.add(slot_id)
    logger.debug(f"Shop purchase: {slot_id}")
    save_shop_state(ctx)
    write_aom_state(ctx)
    # Update GUI gems/shops count immediately after purchase
    if ctx.client_interface is not None:
        from .ApClient import _update_atlantis_ui
        _update_atlantis_ui(ctx.client_interface)

    if "ITEM" in slot_id:
        loc_ids = ctx.shop_obelisk_assignments.get(slot_id, [])
        logger.debug(f"  → checking {len(loc_ids)} item location(s)")
        return loc_ids

    if "HINT" in slot_id:
        _send_shop_hints(ctx, slot_id)
        return []

    return []


def _send_shop_hints(ctx: AoMGameContext, slot_id: str) -> None:
    """Send mission hints or fire Progressive Shop Info check for a purchased hint slot."""
    hint_cfg = ctx.shop_hint_config.get(slot_id)
    if not hint_cfg or ctx.client_interface is None:
        return

    if hint_cfg.get("type") == "progressive_info":
        # This is a Progressive Shop Info purchase — fire the location check
        loc_id = hint_cfg.get("loc_id")
        if loc_id and loc_id not in ctx.sent_checks:
            ctx.sent_checks.add(loc_id)
            save_sent_checks(ctx)
            asyncio.ensure_future(ctx.client_interface.on_location_received(loc_id))
            logger.debug(f"Progressive Shop Info purchased: {slot_id} → location {loc_id}")
            logger.info("Shop Information upgraded! Go back to the shop to see more details.")
        return

    if hint_cfg.get("type") == "mission_hints":
        missions_range = hint_cfg.get("missions_range", (1, 2))
        ctx.client_interface.send_mission_hints(missions_range)


def read_new_checks(ctx: AoMGameContext) -> list[int]:
    """Tail the AoMR AI echo log and return any newly-detected location ids.

    Polls `<user_folder>/MythRetoldAIOutputPlayer12.txt` (where the in-game
    AI's `aiEcho()` output is dumped when `aiDebug` is set in user.cfg).
    Parses for our AP-prefixed tokens:

      AP_CHECK:<id>           — a location was hit; queue it for send.
      AP_LOCKED:<campaign>    — the player tried to enter a locked section;
                                surface a one-shot warning toast.
      AP_SHOP:<slot_id>       — shop purchase; routed via _resolve_shop_signal
                                which converts to location id(s) or a hint
                                broadcast.
      AP_TRAP_FIRED:<idx>     — the running game finished firing a trap
                                from the queue; advance the queue and
                                update aom_state.xs.
      AP_RAND_GP:<scen,tier,gp> — random god power state for status display.

    Returns:
      list[int] of location ids ready to be sent to the AP server.  Side
      effects: updates ctx.sent_checks, ctx.trap_queue, ctx.purchased_slots,
      and writes aom_state.xs / cache state when relevant tokens fire.

    Caller: `game_loop` in this module.
    """
    """
    Read the entire AI output log from byte 0 on every poll.

    The log is purged on connect, so scanning from the start of the recreated
    file is safe and aggressively picks up newly written AP_CHECK lines even if
    offset tracking would otherwise become misaligned.

    Deduplication is still handled by in-memory and persisted state:
      - AP_CHECK / AP_SHOP -> sent_checks and server_known_checks
      - AP_TRAP_FIRED      -> trap_ack_nonce
      - AP_LOCKED          -> locked_warning_campaigns
    """
    import re
    ai_file = ctx.ai_output_file

    if not ai_file.exists():
        return []

    try:
        file_bytes = ai_file.read_bytes()
    except OSError:
        return []

    if not file_bytes:
        return []

    # Ensure even byte count for UTF-16-LE alignment.
    if len(file_bytes) % 2 != 0:
        file_bytes = file_bytes[:-1]

    content = file_bytes.decode("utf-16-le", errors="ignore")

    # If content doesn't end on a line boundary AoM is mid-write; truncate to
    # the last complete line so we never process a partial signal.
    last_newline = max(content.rfind("\n"), content.rfind("\r"))
    if last_newline >= 0 and last_newline < len(content) - 1:
        content = content[:last_newline + 1]

    new_checks = []
    trap_signals = 0   # AP_TRAP_FIRED lines since the last "APAI startup." in this file
    in_current_session = False

    try:
        for line in content.splitlines():
            line = line.strip()
            if not line:
                continue

            # Each new scenario writes "APAI startup." as the first log line.
            # Reset trap counters when we see it so trap handling is scoped to
            # the current scenario.
            if "APAI startup." in line:
                trap_signals = 0
                ctx.trap_ack_nonce = 0
                in_current_session = True
                continue

            # Ignore anything before the first startup line in the current log.
            if not in_current_session:
                continue

            if AP_RAND_GP_PREFIX in line:
                idx = line.find(AP_RAND_GP_PREFIX)
                msg = line[idx + len(AP_RAND_GP_PREFIX):].strip()
                logger.info(f"Random God Power: {msg}")
                continue

            if AP_LOCKED_PREFIX in line:
                m = re.search(r"AP_LOCKED:(\S+)", line)
                campaign = m.group(1) if m else "unknown"
                if campaign not in ctx.locked_warning_campaigns:
                    logger.warning(
                        f"Archipelago: You need the {campaign} Scenarios item to play this campaign."
                    )
                    ctx.locked_warning_campaigns.add(campaign)
                continue

            if "AP_TRAP_FIRED:" in line:
                trap_signals += 1
                continue

            if AP_SHOP_PREFIX in line:
                m = re.search(r"AP_SHOP:IDX:(\d+)", line)
                if m:
                    try:
                        slot_num = int(m.group(1))
                        from ..locations.Locations import SHOP_SLOT_ORDER
                        slot_id = SHOP_SLOT_ORDER[slot_num - 1] if 1 <= slot_num <= len(SHOP_SLOT_ORDER) else ""
                    except (ValueError, IndexError):
                        slot_id = ""
                else:
                    m2 = re.search(r"AP_SHOP:(\S+)", line)
                    slot_id = m2.group(1) if m2 else ""
                if not slot_id:
                    logger.warning(f"Unrecognised shop signal in line: {line!r}")
                    continue
                shop_checks = _resolve_shop_signal(ctx, slot_id)
                for loc_id in shop_checks:
                    if loc_id not in ctx.sent_checks and loc_id not in ctx.server_known_checks:
                        new_checks.append(loc_id)
                        ctx.sent_checks.add(loc_id)
                if shop_checks:
                    save_sent_checks(ctx)
                continue

            m = re.search(r"AP_CHECK:(\d+)", line)
            if not m:
                continue
            loc_id = int(m.group(1))
            if loc_id not in ctx.sent_checks and loc_id not in ctx.server_known_checks:
                new_checks.append(loc_id)
                ctx.sent_checks.add(loc_id)

    except Exception as ex:
        logger.error(f"Failed to parse AI output file: {ex}")

    # Process trap signals: trap_signals counts only AP_TRAP_FIRED lines since
    # the last "APAI startup." line, so it's already scoped to the current
    # scenario. trap_ack_nonce tracks how many we've popped this scenario.
    new_trap_count = max(0, trap_signals - ctx.trap_ack_nonce)
    if new_trap_count > 0:
        for _ in range(new_trap_count):
            if ctx.trap_queue:
                fired = ctx.trap_queue.pop(0)
                logger.debug(f"Trap fired: type {fired}, {len(ctx.trap_queue)} remaining")
            ctx.trap_ack_nonce += 1
        save_trap_state(ctx)
        write_aom_state(ctx)

    if new_checks:
        save_sent_checks(ctx)
    return new_checks

# -----------------------------------------------------------------------
# Items received
# -----------------------------------------------------------------------

def on_items_received(ctx: AoMGameContext, items: list[int]) -> None:
    """Hook fired by ApClient when the AP server sends a fresh ReceivedItems
    batch.  Replaces the entire received_items list (the server always sends
    the full set, not deltas) and regenerates aom_state.xs so the next
    scenario load picks up the new items.

    Args:
        items: the full list of item ids the server says we own (in the
               order they were received).  archipelago.xs reads these as
               `gAPItems[9..]` (after the 9 leading flag slots).
    """
    ctx.received_items = items
    write_aom_state(ctx)


# -----------------------------------------------------------------------
# Game loop
# -----------------------------------------------------------------------

async def game_loop(ctx: AoMGameContext) -> None:
    """Long-running async task spawned per AP connection.

    Heartbeat-polls the AoMR AI echo log every ~2 seconds for new check /
    purchase / trap signals, sends any new locations to the AP server via
    the client_interface, and emits status/progress lines to the log.

    Stops when `ctx.running` flips to False (e.g. on disconnect).

    Caller: `AoMContext._start_game_loop` in ApClient.py.
    """
    logger.info("AoMR game loop started. Watching for scenario completions...")
    logger.info(f"Watching file: {ctx.ai_output_file}")
    logger.info("Age of Mythology: Retold client commands:")
    logger.info("  /status                — show connection info and Atlantis Key progress")
    logger.info("  /progress (/scenarios) — list beaten, in-progress, and untouched scenarios")
    logger.info("  /gods                  — show randomized god per scenario (random_major_gods only)")
    logger.info("  /greek /egypt /norse /atlantean — show unit/myth/age unlock items for that civ")
    logger.info("  /generic               — show all other received items (heroes, resources, etc.)")

    # The log is read from byte 0 on every poll; no offset initialization needed.
    ai_file = ctx.ai_output_file
    while ctx.running:
        new_checks = read_new_checks(ctx)

        if new_checks and ctx.client_interface is not None:
            for loc_id in new_checks:
                loc_name = location_id_to_name.get(loc_id, str(loc_id))
                logger.debug(f"Check found: {loc_name}")
            # Send all new checks in a single LocationChecks batch to avoid
            # rapid-fire individual messages that have caused server disconnects
            # (notably during shop ITEM purchases that yield 2-3 locations at once).
            for attempt in range(3):
                try:
                    await ctx.client_interface.on_locations_received_batch(new_checks)
                    break
                except Exception as ex:
                    if attempt < 2:
                        logger.warning(f"Batch send attempt {attempt+1} failed for {len(new_checks)} check(s): {ex}. Retrying...")
                        await asyncio.sleep(1.0)
                    else:
                        logger.error(f"Failed to send {len(new_checks)} check(s) after 3 attempts: {ex}. Will retry on reconnect.")

        await asyncio.sleep(2.0)